<?php

namespace BOMO\RedirectBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RedirectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedirectRepository extends EntityRepository
{
    public function getFromSource($source)
    {
        $q = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.urlSource = :source')
            ->setParameter('source', $source)
            ->getQuery();

        return $q->getSingleResult();
    }
    
}
